### ISSUE TITLE
Deactivate PIR-Sensor during data transmision

### ISSUE THREAD

**Issue by MeierTobias** [guidosch/lora#34]
Follow up from [https://github.com/guidosch/lora/issues/21#issuecomment-1006514259](https://github.com/guidosch/lora/issues/21#issuecomment-1006514259)

**Comment by guidosch** [comment]
Great idea!

**Comment by MeierTobias** [comment]
Here's the data sheet of the PIR-Sensor for further investigation of this problem.
[https://files.seeedstudio.com/wiki/Grove_PIR_Motion_Sensor/resources/Twig_-_BISS0001.pdf](https://files.seeedstudio.com/wiki/Grove_PIR_Motion_Sensor/resources/Twig_-_BISS0001.pdf)
(Graph of the different trigger modes on page 2 and 3)
